# Generated by Django 2.0.3 on 2018-03-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sksid', models.CharField(max_length=30)),
                ('business_name', models.CharField(max_length=200)),
                ('business_add1', models.CharField(max_length=200)),
                ('business_add2', models.CharField(max_length=50)),
                ('business_city', models.CharField(max_length=50)),
                ('business_state', models.CharField(max_length=50)),
                ('business_zip', models.CharField(max_length=10)),
                ('tech_name', models.CharField(max_length=200)),
                ('ship_add1', models.CharField(max_length=200)),
                ('ship_add2', models.CharField(max_length=50)),
                ('ship_city', models.CharField(max_length=50)),
                ('ship_state', models.CharField(max_length=50)),
                ('ship_zip', models.CharField(max_length=10)),
                ('part_number', models.CharField(max_length=20)),
                ('part_name', models.CharField(max_length=50)),
                ('part_qty', models.IntegerField()),
                ('req_time', models.DateField(auto_now_add=True)),
                ('req_statue', models.BooleanField()),
            ],
        ),
    ]
