# Generated by Django 2.0.3 on 2018-03-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='serial_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='ship_method',
            field=models.CharField(choices=[('NDA', 'NEXT DAY AIR'), ('2NDA', 'SECOND DAY AIR'), ('GROUND', 'GROUND')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='tracking',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
