# Generated by Django 2.0.3 on 2018-03-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20180324_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='req_statue',
            field=models.NullBooleanField(),
        ),
    ]
