# Generated by Django 2.0.3 on 2018-03-28 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20180324_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District Of Columbia'), ('FM', 'Federated States Of Micronesia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MH', 'Marshall Islands'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PW', 'Palau'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=30)),
                ('zipCode', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=200)),
                ('contactName', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Address')),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='business_add1',
        ),
        migrations.RemoveField(
            model_name='request',
            name='business_add2',
        ),
        migrations.RemoveField(
            model_name='request',
            name='business_city',
        ),
        migrations.RemoveField(
            model_name='request',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='business_state',
        ),
        migrations.RemoveField(
            model_name='request',
            name='business_zip',
        ),
        migrations.RemoveField(
            model_name='request',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='request',
            name='part_qty',
        ),
        migrations.RemoveField(
            model_name='request',
            name='req_statue',
        ),
        migrations.RemoveField(
            model_name='request',
            name='req_time',
        ),
        migrations.RemoveField(
            model_name='request',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='request',
            name='ship_add1',
        ),
        migrations.RemoveField(
            model_name='request',
            name='ship_add2',
        ),
        migrations.RemoveField(
            model_name='request',
            name='ship_city',
        ),
        migrations.RemoveField(
            model_name='request',
            name='ship_method',
        ),
        migrations.RemoveField(
            model_name='request',
            name='ship_state',
        ),
        migrations.RemoveField(
            model_name='request',
            name='ship_zip',
        ),
        migrations.RemoveField(
            model_name='request',
            name='sksid',
        ),
        migrations.RemoveField(
            model_name='request',
            name='tech_name',
        ),
        migrations.AddField(
            model_name='request',
            name='SKSID',
            field=models.CharField(default=111, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='partName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='partNumber',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='partQty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='requestStatue',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='request',
            name='requestTime',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='serialNumber',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='shippingMethod',
            field=models.CharField(blank=True, choices=[('NDA', 'NEXT DAY AIR'), ('2NDA', 'SECOND DAY AIR'), ('GROUND', 'GROUND')], max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='customer',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='request.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='shippingAddress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='request.Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='tech',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='request.Person'),
            preserve_default=False,
        ),
    ]
