# Generated by Django 2.0.3 on 2018-04-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partsinv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(blank=True, db_column='Item', null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('group_id', models.TextField(blank=True, db_column='Group_ID', null=True)),
                ('class_id', models.TextField(blank=True, db_column='Class_ID', null=True)),
                ('inventory', models.TextField(blank=True, db_column='Inventory', null=True)),
            ],
            options={
                'db_table': 'partsinv',
                'managed': False,
            },
        ),
    ]
